// src/vue/components/Stopwatch.vue
<template>
  <div>
    <h2>{{ time | number }}</h2>
    <button v-on:click="start" v-bind:disabled="isRunning">Start</button>
    <button v-on:click="stop" v-bind:disabled="!isRunning">Stop</button>
    <button v-on:click="reset">Reset</button>
    <p v-if="elapsedTime + time > 0">Total elapsed time: {{ elapsedTime + time | number }}</p>
  </div>
</template>

<script>
import { IntervalObservable } from 'rxjs/observable/IntervalObservable';
import { Subscription } from 'rxjs/Subscription';
import { Constants } from '../../common';

let subscription = null;

const state = {
  time: 0.0,
  elapsedTime: 0.0,
  isRunning: false
};

const start = () => {
  if (state.isRunning) return;

  state.isRunning = true;
  subscription = IntervalObservable.create(Constants.PERIOD).subscribe(() => state.time += Constants.INCREMENT);
};

const stop = () => {
  if (!state.isRunning) return;

  state.isRunning = false;
  if (subscription) {
    subscription.unsubscribe();
    subscription = null;
  }
};

const reset = () => {
  stop();
  state.elapsedTime += state.time;
  state.time = 0.0;
};

export default {
  name: 'stopwatch',
  data() {
    return state;
  },
  filters: {
    number: value => {
      return value.toFixed(2);
    }
  },
  methods: {
    start,
    stop,
    reset
  }
}
</script>

<style scoped>

</style>

// src/react/components/Stopwatch.jsx
import React from 'react';
import { IntervalObservable } from 'rxjs/observable/IntervalObservable';

import { Constants } from '../../common';

export class Stopwatch extends React.Component {

  subscription = null;

  constructor() {
    super();
  }

  componentWillMount() {
    this.setTime(0.0);
  }

  render() {
    return <div>
      <h2>{ this.state.time.toFixed(2) }</h2>
      <button onClick={this.start.bind(this)} disabled={this.state.active}>Start</button>
      <button onClick={this.stop.bind(this)} disabled={!this.state.active}>Stop</button>
      <button onClick={this.reset.bind(this)}>Reset</button>
      { this.state.elapsedTime + this.state.time > 0 && ( <p>Total elapsed time: { (this.state.elapsedTime + this.state.time).toFixed(2) }</p> ) }
    </div>
  }

  start() {
    this.subscription = IntervalObservable.create(Constants.PERIOD).subscribe(() => {
      this.setTime(this.state.time + Constants.INCREMENT);
    });
    this.setActive(true);
  }

  stop() {
    if (this.subscription) {
      this.subscription.unsubscribe();
    }
    this.subscription = null;
    this.setActive(false);
  }

  reset() {
    this.stop();
    this.state.elapsedTime += this.state.time;
    this.setTime(0.0);
  }

  setTime(time) {
    this.setState({
      elapsedTime: this.elapsedTime,
      time
    });
  }

  setActive(active) {
    this.setState({
      active
    });
  }

  get elapsedTime() {
    return this.state ? this.state.elapsedTime : 0.0;
  }
}
